[package]
name = "crust"
version = "0.1.0"
authors = ["onehrxn <waharaxn@gmail.com>"]
edition = "2018"

[dependencies.structopt]
version = "0.2.15"

[features]
debug = []
ast = []
source = []
token = []
as = []
